#!/usr/bin/env bash
#
# Generates ios/BallotWatch/Secrets.plist from the repo-root .env.
#
# The plist is gitignored — this repo is public, so no key is committed. Run
# this once after cloning, and again whenever a key rotates.
#
#   ios/scripts/make-secrets.sh
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
OUT="$REPO_ROOT/ios/BallotWatch/Secrets.plist"

if [ ! -f "$ENV_FILE" ]; then
  echo "error: no .env at $ENV_FILE" >&2
  echo "Copy .env.example to .env and fill it in first." >&2
  exit 1
fi

# Read without sourcing: .env can contain values that a shell would try to
# expand, and this script only needs three literal strings.
read_env() {
  local key="$1"
  sed -n "s/^${key}=//p" "$ENV_FILE" | head -1 | sed 's/^["'"'"']//; s/["'"'"']$//'
}

SUPABASE_URL="$(read_env VITE_SUPABASE_URL)"
SUPABASE_ANON_KEY="$(read_env VITE_SUPABASE_ANON_KEY)"
CONGRESS_API_KEY="$(read_env VITE_CONGRESS_API_KEY)"

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "error: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set in .env" >&2
  exit 1
fi

if [ -z "$CONGRESS_API_KEY" ]; then
  echo "warning: VITE_CONGRESS_API_KEY not set — House members will show their" >&2
  echo "         state instead of a district number. Free key at" >&2
  echo "         https://api.congress.gov/sign-up/" >&2
fi

cat > "$OUT" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by ios/scripts/make-secrets.sh. Gitignored: do not commit. -->
<plist version="1.0">
<dict>
	<key>SUPABASE_URL</key>
	<string>${SUPABASE_URL}</string>
	<key>SUPABASE_ANON_KEY</key>
	<string>${SUPABASE_ANON_KEY}</string>
	<key>CONGRESS_API_KEY</key>
	<string>${CONGRESS_API_KEY}</string>
</dict>
</plist>
PLIST

echo "Wrote $OUT"
