import { useEffect, useRef } from 'react'
import '../styles/MethodologyModal.css'

/**
 * Single shared methodology modal. Opens to a specific anchor:
 *   - 'committee-survival'  — primary-committee math + confidence floor
 *   - 'bill-path-narrative' — how AI narratives are generated + filter rules
 *   - 'sponsor-activity'    — what bill count means + freshman exclusion
 *
 * Esc + click-outside dismisses; focus returns to the link that opened it.
 */
export default function MethodologyModal({ open, anchor, onClose }) {
  const dialogRef = useRef(null)
  const previouslyFocused = useRef(null)

  useEffect(() => {
    if (!open) return

    previouslyFocused.current = document.activeElement
    dialogRef.current?.focus()

    function onKey(e) {
      if (e.key === 'Escape') onClose?.()
    }
    document.addEventListener('keydown', onKey)
    return () => {
      document.removeEventListener('keydown', onKey)
      if (previouslyFocused.current?.focus) {
        previouslyFocused.current.focus()
      }
    }
  }, [open, onClose])

  if (!open) return null

  return (
    <div className="methodology-overlay" onClick={onClose}>
      <div
        className="methodology-modal"
        role="dialog"
        aria-modal="true"
        aria-labelledby="methodology-title"
        ref={dialogRef}
        tabIndex={-1}
        onClick={(e) => e.stopPropagation()}
      >
        <button
          className="methodology-close"
          aria-label="Close methodology"
          onClick={onClose}
        >
          ×
        </button>
        <h2 id="methodology-title" className="methodology-title">
          <em>Methodology</em>
        </h2>

        <section
          className={`methodology-section ${anchor === 'committee-survival' ? 'methodology-section-active' : ''}`}
          id="committee-survival"
        >
          <h3 className="methodology-h3">Committee survival rate</h3>
          <p>
            We count a bill toward exactly one committee — the one with the earliest
            referral date (ties broken alphabetically by committee code). This avoids
            double-counting bills referred to multiple committees: every bill contributes
            to one primary committee's denominator only.
          </p>
          <p>
            A bill is counted as <strong>advanced</strong> when the routings record shows
            reported_by, discharged_from, or markup activity, OR when the bill's overall
            legislative stage has reached floor consideration or beyond.
          </p>
          <p>
            We only display a percentage when the committee has at least 30 primary
            referrals in the Congress being scored. Below that threshold, we show
            "Insufficient history yet" rather than a noisy number.
          </p>
          <p className="methodology-version">
            Math version: v1. See <code>etl/computeCommitteeSurvival.ts</code> for the
            source implementation.
          </p>
        </section>

        <section
          className={`methodology-section ${anchor === 'bill-path-narrative' ? 'methodology-section-active' : ''}`}
          id="bill-path-narrative"
        >
          <h3 className="methodology-h3">"Where this bill goes" narrative</h3>
          <p>
            Each narrative is generated by gpt-4o-mini and grounded in three structured
            inputs: the bill's committee routings, the bill's current legislative stage,
            and the primary committee's historical survival rate. The model never
            invents a percentage — it can only cite numbers we passed in.
          </p>
          <p>
            A forbidden-word filter (bias, biased, anti-American, corruption,
            influence-peddling) runs on every generation. If the first attempt matches,
            we retry once. If the retry also fails, we substitute a deterministic
            template sentence so the section never ships politically-loaded language.
          </p>
          <p>
            Narratives are cached per (bill, prompt_version). Bumping the prompt version
            writes a new row; old rows stay for audit. The version is shown as a small
            suffix on the marginalia label.
          </p>
        </section>

        <section
          className={`methodology-section ${anchor === 'sponsor-activity' ? 'methodology-section-active' : ''}`}
          id="sponsor-activity"
        >
          <h3 className="methodology-h3">Sponsor activity badge</h3>
          <p>
            The count is bills where this member is the primary sponsor, in the current
            Congress only. Cosponsorship is not included — that keeps the "sponsor
            activity" label honest.
          </p>
          <p>
            The chamber median compares against all members who have served at least 30
            days. Freshmen and mid-cycle replacements are excluded from the median pool
            to avoid degenerate denominators, but their own count is still rendered.
          </p>
          <p>
            Bill count includes messaging bills and resolutions. It is not a measure of
            effectiveness — passing a single major bill counts the same as introducing
            ten resolutions that never reach committee markup.
          </p>
        </section>
      </div>
    </div>
  )
}
