// The factual outline for a message to a member of Congress.
//
// Rules (see docs/designs/agent-front-door-and-tell-your-rep.md, Phase 4):
// the person writes the message. This outline states only facts from the
// record — which vote or bill, how this member voted, the result, the official
// source — and leaves a bracketed line for the person's own words. It never
// picks a side, never argues, and is never generated by a model.

export const OWN_WORDS_LINE = '[Write your message here, in your own words.]'
export const SIGNATURE_LINES = ['[Your name]', '[Your street address, city, ZIP]']

const ORD = (n) => {
  const v = Number(n) % 100
  const s = ['th', 'st', 'nd', 'rd']
  return `${n}${s[(v - 20) % 10] || s[v] || s[0]}`
}

export function normalizeChamber(value) {
  const s = String(value || '').toLowerCase()
  if (s.includes('senate')) return 'senate'
  if (s.includes('house') || s.includes('representative')) return 'house'
  return null
}

/** "Bean, Aaron" → "Aaron Bean"; "Robert Aderholt" stays. */
export function displayName(name) {
  const s = String(name || '').trim()
  if (!s.includes(',')) return s
  const [last, ...rest] = s.split(',')
  const first = rest.join(',').trim()
  return first ? `${first} ${last.trim()}` : last.trim()
}

export function lastName(member) {
  if (member?.lastName) return String(member.lastName).trim()
  const s = String(member?.name || '').trim()
  if (s.includes(',')) return s.split(',')[0].trim()
  const parts = s.split(/\s+/).filter((p) => !/^(jr\.?|sr\.?|ii|iii|iv)$/i.test(p))
  return parts[parts.length - 1] || s
}

export function memberTitle(member) {
  return normalizeChamber(member?.chamber) === 'senate' ? 'Senator' : 'Representative'
}

/** "TX-7", "AK-AL", or "TX" for a senator. */
export function seatLabel(member) {
  const state = member?.state ? String(member.state).toUpperCase() : ''
  if (!state) return ''
  if (normalizeChamber(member?.chamber) === 'senate') return state
  const d = member?.district
  if (d === null || d === undefined || d === '') return state
  return String(d) === '0' ? `${state}-AL` : `${state}-${Number(d)}`
}

export function formatDate(value) {
  if (!value) return ''
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return ''
  return d.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' })
}

/** Stable, anonymous reference for analytics: `vote:119-house-2-295`, `bill:119-hr-1`, `member:B001314`. */
export function voteRef({ congress, chamber, session, roll }) {
  return `vote:${Number(congress)}-${String(chamber).toLowerCase()}-${Number(session)}-${Number(roll)}`
}
export function billRef({ congress, billType, number }) {
  return `bill:${Number(congress)}-${String(billType).toLowerCase()}-${Number(number)}`
}
export function memberRef(bioguideId) {
  return `member:${String(bioguideId).toUpperCase()}`
}

const BILL_TYPE_SLUGS = {
  hr: 'house-bill',
  s: 'senate-bill',
  hres: 'house-resolution',
  sres: 'senate-resolution',
  hjres: 'house-joint-resolution',
  sjres: 'senate-joint-resolution',
  hconres: 'house-concurrent-resolution',
  sconres: 'senate-concurrent-resolution',
}

/** Public Congress.gov page for a bill (the API's `bill.url` points at api.congress.gov). */
export function congressGovBillUrl(congress, billType, number) {
  const slug = BILL_TYPE_SLUGS[String(billType || '').toLowerCase()]
  if (!slug || !Number(congress) || !Number(number)) return null
  return `https://www.congress.gov/bill/${ORD(Number(congress))}-congress/${slug}/${Number(number)}`
}

const POSITION_WORDS = {
  yea: 'Yea', aye: 'Yea', yes: 'Yea',
  nay: 'Nay', no: 'Nay',
  present: 'Present',
  'not voting': 'Not Voting',
}
function normalizePosition(p) {
  const key = String(p || '').trim().toLowerCase()
  return POSITION_WORDS[key] || (p ? String(p).trim() : '')
}

/**
 * The member's own vote on this roll call, from `memberVote` (single-member
 * pages) or `memberVotes[bioguideId]` (the roll-call page).
 */
export function voteFor(context, member) {
  if (!context || !member) return ''
  const fromMap = context.memberVotes && member.bioguideId ? context.memberVotes[member.bioguideId] : null
  return normalizePosition(fromMap || context.memberVote || '')
}

/**
 * Build the outline.
 *
 * @param {object} args
 * @param {object} args.context  TellYourRep context
 * @param {object} args.member   { name, lastName?, chamber, state, district? }
 * @param {boolean} [args.constituent] true when the member was found from the person's own location
 * @param {string} [args.origin] site origin, used only when there is no official source URL
 */
export function buildScaffold({ context, member, constituent = false, origin = '' }) {
  const lines = []
  const title = memberTitle(member)
  const surname = lastName(member)
  lines.push(`Dear ${title}${surname ? ` ${surname}` : ''},`, '')

  const seat = seatLabel(member)
  const intro = []
  if (constituent && seat) intro.push(`I am a constituent in ${seat}.`)

  const kind = context?.kind
  const memberChamber = normalizeChamber(member?.chamber)
  const voteChamber = normalizeChamber(context?.chamber)

  if (kind === 'vote') {
    const when = formatDate(context.date)
    const subject = context.title ? `: ${context.title}` : ''
    intro.push(`I am writing about ${context.label}${when ? `, held ${when}` : ''}${subject}.`)
  } else if (kind === 'bill') {
    intro.push(`I am writing about ${context.label}${context.title ? `, ${context.title}` : ''}.`)
  } else {
    intro.push('I am writing about [the bill, vote, or issue you want to raise].')
  }
  lines.push(intro.join(' '), '')

  const facts = []
  if (kind === 'vote') {
    const position = voteFor(context, member)
    if (position) facts.push(`Your recorded vote: ${position}.`)
    else if (voteChamber && memberChamber && voteChamber !== memberChamber) {
      facts.push(`This was a ${voteChamber === 'house' ? 'House' : 'Senate'} vote, so you did not vote on it.`)
    }
    if (context.result) facts.push(`Result: ${context.result}.`)
  } else if (kind === 'bill') {
    if (context.result) facts.push(`Latest action: ${context.result}`)
  }
  const source = kind === 'member' ? '' : (context?.sourceUrl || (context?.href ? `${origin}${context.href}` : ''))
  if (source) facts.push(`Official record: ${source}`)
  if (facts.length) lines.push(...facts, '')

  lines.push(OWN_WORDS_LINE, '', 'Sincerely,', ...SIGNATURE_LINES)
  return lines.join('\n')
}
