-- =============================================================================
-- Migration: Add voting dashboard columns and tables
-- =============================================================================
-- This migration adds the schema required by the 538-style voting dashboard:
--   1. roll_call_id column on votes table (for ETL dedup)
--   2. crs_summary and policy_area columns on bills table
--   3. member_stats table (pre-computed voting statistics)
--   4. etl_metadata table (ETL run tracking)
--
-- Safe to run multiple times (uses IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).
-- Run this in your Supabase SQL Editor.
-- =============================================================================


-- =============================================================================
-- 1. VOTES TABLE: Add roll_call_id column
-- =============================================================================

ALTER TABLE votes ADD COLUMN IF NOT EXISTS roll_call_id TEXT;

-- Primary dedup key for the ETL. Format: "{chamber}-{congress}-{session}-{rollNumber}"
-- e.g., "senate-119-1-42"
CREATE UNIQUE INDEX IF NOT EXISTS idx_votes_roll_call_politician
  ON votes(roll_call_id, politician_id);


-- =============================================================================
-- 2. BILLS TABLE: Add crs_summary and policy_area columns
-- =============================================================================

ALTER TABLE bills ADD COLUMN IF NOT EXISTS crs_summary TEXT;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS policy_area TEXT;

CREATE INDEX IF NOT EXISTS idx_bills_policy_area ON bills(policy_area);


-- =============================================================================
-- 3. MEMBER_STATS TABLE
-- =============================================================================
-- Pre-computed per-member voting statistics, generated by the ETL.

CREATE TABLE IF NOT EXISTS member_stats (
  politician_id TEXT NOT NULL REFERENCES politicians(id) ON DELETE CASCADE,
  congress INTEGER NOT NULL,
  total_votes INTEGER DEFAULT 0,
  yea_count INTEGER DEFAULT 0,
  nay_count INTEGER DEFAULT 0,
  present_count INTEGER DEFAULT 0,
  not_voting_count INTEGER DEFAULT 0,
  party_loyalty_pct INTEGER DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (politician_id, congress)
);

ALTER TABLE member_stats ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'member_stats' AND policyname = 'Member stats are viewable by everyone'
  ) THEN
    CREATE POLICY "Member stats are viewable by everyone"
      ON member_stats FOR SELECT
      USING (true);
  END IF;
END $$;

GRANT SELECT ON member_stats TO anon;
GRANT ALL ON member_stats TO service_role;


-- =============================================================================
-- 4. ETL_METADATA TABLE
-- =============================================================================
-- Tracks ETL run state (last successful run, etc.)

CREATE TABLE IF NOT EXISTS etl_metadata (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE etl_metadata ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'etl_metadata' AND policyname = 'ETL metadata is viewable by everyone'
  ) THEN
    CREATE POLICY "ETL metadata is viewable by everyone"
      ON etl_metadata FOR SELECT
      USING (true);
  END IF;
END $$;

GRANT SELECT ON etl_metadata TO anon;
GRANT ALL ON etl_metadata TO service_role;


-- =============================================================================
-- 5. UPDATE VIEWS AND FUNCTIONS
-- =============================================================================

-- Update recent_votes_with_details view to include roll_call_id
CREATE OR REPLACE VIEW recent_votes_with_details AS
SELECT
  v.id,
  v.position,
  v.voted_at,
  v.roll_call_id,
  v.source_url AS vote_source_url,
  p.id AS politician_id,
  p.name AS politician_name,
  p.chamber,
  p.state,
  p.district,
  p.party,
  p.photo_url,
  b.id AS bill_id,
  b.title AS bill_title,
  b.summary AS bill_summary,
  b.crs_summary AS bill_crs_summary,
  b.policy_area AS bill_policy_area,
  b.source_url AS bill_source_url
FROM votes v
JOIN politicians p ON v.politician_id = p.id
LEFT JOIN bills b ON v.bill_id = b.id
ORDER BY v.voted_at DESC;

-- Update get_politician_votes function to return new columns
CREATE OR REPLACE FUNCTION get_politician_votes(
  p_politician_id TEXT,
  p_limit INT DEFAULT 20
)
RETURNS TABLE (
  vote_id BIGINT,
  vote_position TEXT,
  voted_at DATE,
  roll_call_id TEXT,
  vote_source_url TEXT,
  bill_id TEXT,
  bill_title TEXT,
  bill_summary TEXT,
  bill_crs_summary TEXT,
  bill_policy_area TEXT,
  bill_source_url TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    v.id AS vote_id,
    v.position AS vote_position,
    v.voted_at,
    v.roll_call_id,
    v.source_url AS vote_source_url,
    b.id AS bill_id,
    b.title AS bill_title,
    b.summary AS bill_summary,
    b.crs_summary AS bill_crs_summary,
    b.policy_area AS bill_policy_area,
    b.source_url AS bill_source_url
  FROM votes v
  LEFT JOIN bills b ON v.bill_id = b.id
  WHERE v.politician_id = p_politician_id
  ORDER BY v.voted_at DESC
  LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;
